---
- name: Downlaod files
  hosts: Testing

  tasks:
  - name: Download file
    get_url:
      url: https://www.python.org/ftp/python/3.12.2/Python-3.12.2.tar.xz
      dest: /tmp/script/
      owner: juju
      group: juju
      mode: 0777
