---
- name: Kill a process
  hosts: Testing
  vars:
    app_name: nginx

  tasks:
  - name: Find a process and kill it
    ignore_errors: yes
    shell: "pgrep nginx | xargs kill"

  - name: Find a process and kill it using variable
    ignore_errors: yes
    shell: "pgrep {{ app_name }} | xargs kill"

  - name: Start the service
    service:
      name: "{{ app }}"
      state: started
