---
- name: Install and Start the service
  hosts: localhost
  
  tasks:
  - name: Installing nginx
    apt:
      name: nginx
      state: present
    tags: install-nginx

  - name: Start nginx service
    service:
      name: nginx
      state: started
      enabled: true
    tags: start-nginx