---
- hosts: webservers
  become: true
  tasks:

    - name: Create a scheduled task
      cron:
        name: "Run employee attendance"
        job: "sh /opt/scripts/attendance.sh"
        month: "*"
        day: "*"
        hour: "17"
        minute: "00"
