---
- name: Check for available updates on Debian and RedHat systems
  hosts: all
  become: yes
  tasks:
    - name: Gather facts about the system
      ansible.builtin.gather_facts:

    - name: Get the hostname of the system
      shell: uname -n
      register: system_hostname

    - name: Check for available updates on Debian-based systems
      shell: apt list --upgradable
      when: ansible_os_family == 'Debian'
      register: debian_updates
      ignore_errors: yes

    - name: Check for available updates on RedHat-based systems (dnf)
      shell: dnf list updates
      when: 
        - ansible_os_family == 'RedHat'
        - ansible_distribution != 'Rocky'
      register: redhat_updates
      ignore_errors: yes

    - name: Check for available updates on Rocky Linux
      shell: dnf check-update
      when: ansible_distribution == 'Rocky'
      register: rocky_updates
      ignore_errors: yes
      failed_when: rocky_updates.rc not in [0, 100]

    - name: Ensure patchlist file exists on 10.1.34.26
      ansible.builtin.file:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        state: touch
      delegate_to: 10.1.34.26

    - name: Clear patchlist file on 10.1.34.26
      ansible.builtin.copy:
        dest: /home/svc_aux/backup/patchinformation/patchlist.txt
        content: ""
      delegate_to: 10.1.34.26

    - name: Format and write updates to patchlist file for Debian
      ansible.builtin.lineinfile:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        line: |
          -----------------------------------
          Hostname: {{ system_hostname.stdout }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Available Updates:
          {{ debian_updates.stdout | default('No updates available') }}
          -----------------------------------
      when: 
        - ansible_os_family == 'Debian'
        - inventory_hostname != '10.1.34.26'
      delegate_to: 10.1.34.26

    - name: Format and write updates to patchlist file for Rocky Linux
      ansible.builtin.lineinfile:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        line: |
          -----------------------------------
          Hostname: {{ system_hostname.stdout }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Available Updates:
          {{ rocky_updates.stdout | default('No updates available') }}
          -----------------------------------
      when: 
        - ansible_distribution == 'Rocky'
        - inventory_hostname != '10.1.34.26'
      delegate_to: 10.1.34.26

    - name: Format and write updates to patchlist file for other RedHat systems
      ansible.builtin.lineinfile:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        line: |
          -----------------------------------
          Hostname: {{ system_hostname.stdout }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Available Updates:
          {{ redhat_updates.stdout | default('No updates available') }}
          -----------------------------------
      when: 
        - ansible_os_family == 'RedHat'
        - ansible_distribution != 'Rocky'
        - inventory_hostname != '10.1.34.26'
      delegate_to: 10.1.34.26

- name: Convert CSV to HTML on remote server
  hosts: 10.1.34.26
  remote_user: svc_aux
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  tasks:
    - name: Wait for CSV file to be created
      wait_for:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        state: present
        timeout: 600  # Increase timeout if needed

    - name: Convert CSV to HTML
      command: python3 /home/svc_aux/backup/patchinformation/convert_to_html.py
      args:
        chdir: /home/svc_aux/backup/patchinformation/
