---
- name: Servis Durumu
  hosts: all
  become: yes
  vars_prompt:
    - name: service_name
      prompt: "Lütfen kontrol etmek istediğiniz servis adını girin:"

  tasks:
    - name: Servis Durumunu Kontrol Et
      systemd:
        name: "{{ service_name }}"
        state: started # Servis durumunu kontrol etmek için 'status' kullanın
      register: service_status

    - name: Servis Durumu Çıktısını Göster
      debug:
        msg: "{{ service_name }} servisi durumu: {{ service_status }}"
