---
- name: Servis Durumu Durdurma
  hosts: all
  become: yes
  vars_prompt:
    - name: service_name
      prompt: "Lütfen kontrol etmek istediğiniz servis adını girin:"

  tasks:
    - name: Servis Durumunu Durdurma
      systemd:
        name: "{{ service_name }}"
        state: stopped
      register: service_status

